name: ProviderLint Checks

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths:
      - .github/workflows/providerlint.yml
      - GNUmakefile
      - go.sum
      - internal/**
      - names/**

jobs:
  providerlint:
    runs-on: [custom, linux, medium]
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version-file: go.mod
      - name: go env
        run: echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ${{ env.GOCACHE }}
          key: ${{ runner.os }}-GOCACHE-${{ hashFiles('go.sum') }}-${{ hashFiles('internal/**') }}
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: cd .ci/providerlint && go install -buildvcs=false .
      - run: make providerlint
