name: Workflow Linting
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .github/workflows/*
      - .ci/tools/go.mod
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version-file: .ci/tools/go.mod
      - name: Install actionlint
        run: cd .ci/tools && go install github.com/rhysd/actionlint/cmd/actionlint
      - name: Run actionlint on workflow files
        run: actionlint -shellcheck=
