name: YAML Linting
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - "**/*.yml"
      - ".yamllint"
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          format: github
        env:
          LANG: C.UTF-8
